project_name: monkey
builds:
- env:
  - CGO_ENABLED=0
  - GRPCHOST=api.fuzzymonkey.co:7077
  goos:
  - darwin
  # TODO: - freebsd openbsd netbsd dragonfly
  - linux
  - windows
  goarch:
  - 386
  - amd64
  # TODO: - arm arm64
  # TODO: goarm: [6, 7]
  ignore: []
  ldflags: >
    -s
    -w
    -extldflags "-static"
    -X main.binVersion={{.Env.CURRENT_TAG}}
    -X github.com/FuzzyMonkeyCo/monkey/pkg/internal/fm.grpcHost={{.Env.GRPCHOST}}

archives:
- replacements:
    # https://en.wikipedia.org/wiki/Uname
    # uname -m compatible.
    386: i386
    amd64: x86_64
    # uname -s compatible.
    # arm64: aarch64
    darwin: Darwin
    dragonfly: DragonFly
    freebsd: FreeBSD
    linux: Linux
    netbsd: NetBSD
    openbsd: OpenBSD
    windows: Windows
  format_overrides:
  - goos: windows
    format: zip
# name_template: '{{.ProjectName}}-{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}'
  name_template: '{{.ProjectName}}-{{.Os}}-{{.Arch}}'
  files:
  - LICENSE
  - README.md

checksum:
  name_template: checksums.sha256.txt
  algorithm: sha256

signs:
- artifacts: none

# TODO: homebrew
# TODO: snap
# TODO: apt
