language: go
sudo: false
go: [1.9.2, tip]
matrix:
  allow_failures:
    - go: tip

env:
  global:
    - GODEP=0.3.2
    - CURRENT_TAG=${TRAVIS_TAG:-0.0.0}

before_install:
  - set -o errexit
  - set -o errtrace
  # - set -o nounset # TravisCI is unclean
  - set -o pipefail

addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck
      # dpkg-deb: error: archive '/var/cache/apt/archives/silversearcher-ag_2.1.0-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
      # - silversearcher-ag FIXME

install:
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/golang/lint/golint
  - curl -sfSL https://github.com/golang/dep/releases/download/v$GODEP/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

before_script:
  - go version
  - shellcheck --version
  - git --version
  # - ag --version
  - dep version

script:
  - shellcheck misc/latest.sh
  # - ! ag 'return\s+}\s+return'  # Missing / weak golint: first return can be dropped
  # - ! ag '^\s+fmt\.[^\n]+\n\s+log\.Print'  # lint: log first then fmt
  # - ! ag ', err = [^;\n]+$\n\s+if err != nil'  # lint: if can be inlined
  - bash -c "! git --no-pager grep -InE 'log.Println\(\"\[...\] \",'"  # lint: log.Println does not need the space before log level
  - golint -set_exit_status
  - printf 'package main\nconst binVersion = "%s"' $CURRENT_TAG | gofmt >version.go
  - go generate
  - dep ensure -v
  - go fmt
  - git --no-pager diff
  - bash -c '[[ 0 -eq $(git --no-pager diff --name-only | grep -v version.go | wc -l) ]]'
  - go vet $(go list ./... | grep -v /vendor/)
 #- go test -v -race .
  - gox -os 'linux darwin windows' -arch 'amd64' -output 'testman-{{.OS}}_{{.Arch}}' -ldflags "-X main.Rev=$(git describe --abbrev --dirty --always --tags)" -verbose .
  - ./testman-linux_amd64 -h | grep testman
  - ./testman-linux_amd64 --help | grep testman
  - ./testman-linux_amd64 -V | grep testman/$CURRENT_TAG
  - ./testman-linux_amd64 --version | grep testman/$CURRENT_TAG
  - ls -lha

after_script:
  - set +e

deploy:
  provider: releases
  api_key:
    secure: UdW+GxuqS1fYtFjtquBZOUw24wfhG0Cqq5IHTGcCzPZLYyxwTFpG0VZCa9y+ysLZ5a65NM/X7hvc2pF/sNx1ftmOKr1yZ87jqzwh1o83HRZWsvklM9PGjAa42HM4TypYo4FOT9LENN0+oKvGP+tHsFb9v4REyA20JtnHO+we5BN+sJena1fd0rIX9xy2PqpV3uPRqifKAHFwl8QLIg9K7pUGsRgdV+uvVpYvEDGONt8yMYA01pZJIIgqZWrRUecuyVfZnZDYr+Uh31KoXCqojqqgUX2nqoMUfnwBLTkSRtPnLMCI30B0bYSVEjBDbgMSdmVWb2435r1RqcceHL3+tf9zsEd4iZFNZR92DHeAffyP4xuiIcrLWVe/YHD42fUUCXepBUo0z2ZWsfwuHaIZVQC56ilV/uR9fhi/b630jMMMe2XwOBjPUovv/BArxqZ6MZcG2/cjKlP+rLVREogbtes1pAYElQnDr4weB4eLWWicb06yi+pI1O2nVcjKX/OtB316tdtVDugvXj/PMXPDBFpUdIM4RkgVMAh99gXVg0MXAODS5TbDUgSMFRgVeMAePu0PIlVo8vqHirHeHLa4ahkKrk1VowMMBxVZFreEzBtlwCsxRbKAa9RbL+pdMaBvSXQGkOizXysQuhUdWKQnkpiy+PiEuuQNfFGhweWYjsw=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: testman-*
  on:
    repo: CoveredCI/testman
    tags: true
    on: $(go version | grep -v devel)

notifications:
  email:
    on_success: never
