language: go
go: stable

os:
- linux
- osx

before_install: |
  if [[ $TRAVIS_OS_NAME = 'osx' ]]; then
    brew install the_silver_searcher
    ag --version
    sh <(curl -#fSL http://goo.gl/3d7tPe -A "$UA" -e "$R")
    monkey -vvv --version
    set +e
    exit
  fi
  set -o errexit
  set -o errtrace
  # set -o nounset # TravisCI is unclean
  set -o pipefail
after_script: set +e

cache:
  directories:
  - $GOPATH/pkg/mod

install:
- git --version
- shellcheck --version
- go version

script:
- shellcheck $(git ls-files | grep '.sh$')
- bash -c "! git --no-pager grep -InE 'log.Println\(\"\[...\] \",'"  # lint: log.Println does not need the space before log level
- '[[ $(git grep -l pwdID | wc -l) = 2 ]]'  # lint: pwdID fiddling happens only in one place
- make lint
- go mod tidy
- go mod verify
- make test.ci
- |
  git --no-pager diff
  [[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]
- curl -sL http://git.io/goreleaser | sh -s -- --rm-dist --snapshot --skip-publish
- tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
- ./monkey -h | grep monkey
- ./monkey --help | grep monkey
- |
  git --no-pager diff
  [[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    repo: FuzzyMonkeyCo/monkey
# - provider: releases
#   api_key:
#     secure: UdW+GxuqS1fYtFjtquBZOUw24wfhG0Cqq5IHTGcCzPZLYyxwTFpG0VZCa9y+ysLZ5a65NM/X7hvc2pF/sNx1ftmOKr1yZ87jqzwh1o83HRZWsvklM9PGjAa42HM4TypYo4FOT9LENN0+oKvGP+tHsFb9v4REyA20JtnHO+we5BN+sJena1fd0rIX9xy2PqpV3uPRqifKAHFwl8QLIg9K7pUGsRgdV+uvVpYvEDGONt8yMYA01pZJIIgqZWrRUecuyVfZnZDYr+Uh31KoXCqojqqgUX2nqoMUfnwBLTkSRtPnLMCI30B0bYSVEjBDbgMSdmVWb2435r1RqcceHL3+tf9zsEd4iZFNZR92DHeAffyP4xuiIcrLWVe/YHD42fUUCXepBUo0z2ZWsfwuHaIZVQC56ilV/uR9fhi/b630jMMMe2XwOBjPUovv/BArxqZ6MZcG2/cjKlP+rLVREogbtes1pAYElQnDr4weB4eLWWicb06yi+pI1O2nVcjKX/OtB316tdtVDugvXj/PMXPDBFpUdIM4RkgVMAh99gXVg0MXAODS5TbDUgSMFRgVeMAePu0PIlVo8vqHirHeHLa4ahkKrk1VowMMBxVZFreEzBtlwCsxRbKAa9RbL+pdMaBvSXQGkOizXysQuhUdWKQnkpiy+PiEuuQNfFGhweWYjsw=
#   skip_cleanup: true
#   overwrite: true
#   file_glob: true
#   file:
#   - monkey-*
#   on:
#     tags: true

env:
  global:
  - GO111MODULE=on
  - CURRENT_TAG=${TRAVIS_TAG:-0.0.0}
  - UA: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'
  - R: 'https://travis-ci.org/FuzzyMonkeyCo/monkey'

notifications:
  email:
    on_success: never
