sudo: false
language: go
go: 1.9.2

env:
  global:
    - CURRENT_TAG=${TRAVIS_TAG:-0.0.0}

before_install:
  - set -o errexit
  - set -o errtrace
  # - set -o nounset # TravisCI is unclean
  - set -o pipefail

addons:
  apt:
    sources:
      - debian-sid # shellcheck
    packages:
      - shellcheck
      # dpkg-deb: error: archive '/var/cache/apt/archives/silversearcher-ag_2.1.0-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
      # - silversearcher-ag FIXME

before_cache:
  - rm -rf $GOPATH/src/github.com/$TRAVIS_REPO_SLUG/*
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - make deps
  - go version
  - shellcheck --version
  - git --version
  # - ag --version
  - dep version

script:
  - shellcheck $(find . -name '*.sh')
  - bash -c "! git --no-pager grep -InE 'log.Println\(\"\[...\] \",'"  # lint: log.Println does not need the space before log level
  - '[[ $(git grep -l pwdID | wc -l) = 2 ]]'  # lint: pwdID fiddling happens only in one place
  - make vendor
  - go fmt && git --no-pager diff
  - '[[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]'
  - make lint
  - go vet $(go list ./... | grep -v /vendor/)
  - megacheck -show-ignored -unused.exported
 #- go test -v -race .
  - make x
  - '[[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]'
  - ./monkey-Linux-x86_64 -h | grep monkey
  - ./monkey-Linux-x86_64 --help | grep monkey
  - ./monkey-Linux-x86_64 -V | grep monkey/$CURRENT_TAG
  - ./monkey-Linux-x86_64 --version | grep monkey/$CURRENT_TAG

after_script:
  - set +e

deploy:
  provider: releases
  api_key:
    secure: UdW+GxuqS1fYtFjtquBZOUw24wfhG0Cqq5IHTGcCzPZLYyxwTFpG0VZCa9y+ysLZ5a65NM/X7hvc2pF/sNx1ftmOKr1yZ87jqzwh1o83HRZWsvklM9PGjAa42HM4TypYo4FOT9LENN0+oKvGP+tHsFb9v4REyA20JtnHO+we5BN+sJena1fd0rIX9xy2PqpV3uPRqifKAHFwl8QLIg9K7pUGsRgdV+uvVpYvEDGONt8yMYA01pZJIIgqZWrRUecuyVfZnZDYr+Uh31KoXCqojqqgUX2nqoMUfnwBLTkSRtPnLMCI30B0bYSVEjBDbgMSdmVWb2435r1RqcceHL3+tf9zsEd4iZFNZR92DHeAffyP4xuiIcrLWVe/YHD42fUUCXepBUo0z2ZWsfwuHaIZVQC56ilV/uR9fhi/b630jMMMe2XwOBjPUovv/BArxqZ6MZcG2/cjKlP+rLVREogbtes1pAYElQnDr4weB4eLWWicb06yi+pI1O2nVcjKX/OtB316tdtVDugvXj/PMXPDBFpUdIM4RkgVMAh99gXVg0MXAODS5TbDUgSMFRgVeMAePu0PIlVo8vqHirHeHLa4ahkKrk1VowMMBxVZFreEzBtlwCsxRbKAa9RbL+pdMaBvSXQGkOizXysQuhUdWKQnkpiy+PiEuuQNfFGhweWYjsw=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - monkey-*
  on:
    repo: FuzzyMonkeyCo/monkey
    tags: true

notifications:
  email:
    on_success: never
