language: go
go: stable

os:
- linux
- osx

before_install: |
  if [[ $TRAVIS_OS_NAME = 'osx' ]]; then
    brew install the_silver_searcher
    ag --version
    curl -#fL https://git.io/FuzzyMonkey | BINDIR=$GOPATH/bin sh -ex
    monkey help
    $GOPATH/bin/monkey version
    exit
  fi

cache:
  directories:
  - $GOPATH/pkg/mod

install:
- git --version
- shellcheck --version
- go version
- curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=$GOPATH/bin sh

script:
- godownloader -r FuzzyMonkeyCo/monkey -o .godownloader.sh .goreleaser.yml
- shellcheck $(git ls-files | grep '.sh$' | grep -vF .godownloader.sh) #TODO: fix godownloader warnings upstream

env:
  global:
  - GO111MODULE=on

notifications:
  email:
    on_success: never
