language: go
go: stable

os:
- linux
- osx

before_install: |
  if [[ $TRAVIS_OS_NAME = 'osx' ]]; then
    brew install the_silver_searcher
    ag --version
    curl -#fL https://git.io/FuzzyMonkey | BINDIR=$GOPATH/bin sh -ex
    monkey -vvv --version
    exit
  fi
  set -o errtrace
  # set -o nounset # TravisCI is unclean
  set -o pipefail

cache:
  directories:
  - $GOPATH/pkg/mod

install:
- git --version
- shellcheck --version
- go version

script:
- shellcheck $(git ls-files | grep '.sh$' | grep -vF .godownloader.sh)
- bash -c "! git --no-pager grep -InE 'log.Println\(\"\[...\] \",'"  # lint: log.Println does not need the space before log level
- '[[ $(git grep -l pwdID | wc -l) = 2 ]]'  # lint: pwdID fiddling happens only in one place
- make lint
- go mod tidy
- go mod verify
- make test.ci
- |
  git --no-pager diff
  [[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]
- curl -sL http://git.io/goreleaser | sh -s -- --rm-dist --snapshot --skip-publish
- tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
- ./monkey -h | grep monkey
- ./monkey --help | grep monkey
- |
  # FIXME: --rm-dist doesn't seem to be doing its job
  ls -lha ./dist
  rm -rf ./dist
- |
  git --no-pager diff
  [[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    repo: FuzzyMonkeyCo/monkey

env:
  global:
  - GO111MODULE=on
  - CURRENT_TAG=${TRAVIS_TAG:-0.0.0}
  # GITHUB_TOKEN
  - secure: 'wnDny6IXiRwSRLun7/AyX7LyvXoWqRMjc/mw3AnYsy7YOMpCBKTUpCOzdt9QtgVDi1jamDR1vmY3fVmO5kLqeKxK32t7jgVepLpEOt43H4ithNKHOJwi2BG0dav3yXfW6Igjp7DaioiK65mCqfiFiOChpP9y4gJPBCMvCK3bHvyop3WrNlpw7yHN7oouUxg4HlHi7pG0wDuvbFy2CMUsdbreRivheYoZ2OUi2AnwQmiN0Knx8e+Cl41whT+CCI6Li3yeRQVjhReC47pIbIcm71e1pxl2ULSfIojbus6LVs6dm1mSGWpxN2f9Fsjatorj6gKkqWrYjtUlv270VX55y8XPYNA4Fb/tg8dmNPKudJ4Yd7rr/xUvU+xcUHh0h+jUTDKElEJOmXUXdgCWUzXhIAB0gUX6uz3+N46v/YknXFL2AnmL5Vxi8neDpS8WBYclLN/utPlA2rQgTlrBaMGJ9F8SpuClVtW4abnGWbJD+Lngrc4mNqBcIp8bDS+FdOm2QFZ5vTj9S4uuWxuaMvHDX+C+6nqG5QziwCXfQ6Q/eMQcEpqe3gwCDktyDO3CJ7v3GlXn14RAfOepopQqj9hKOsfcUxS+6mf6KiQWRtv+msQ5LHP0O3En7qTDu1UOUvnHiI4ZoSJhl3YLNrvy4S9oSQunlPD4NUDNrqapbziEUP8='

notifications:
  email:
    on_success: never
