
[[constraint]]
  branch = "master"
  name = "github.com/sebcat/har"

[[constraint]]
  branch = "master"
  name = "github.com/cardigann/harhar"

[[constraint]]
  version = "2.0.1"
  name = "github.com/aymerick/raymond"

[[constraint]]
  version = "3.5.1"
  name = "github.com/blang/semver"

[[constraint]]
  version = "0.6.2"
  name = "github.com/docopt/docopt.go"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/logutils"

[[constraint]]
  branch = "master"
  name = "github.com/savaki/jq"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "v2"
  name = "github.com/go-yaml/yaml"
