# File for use by https://github.com/golang/dep
# Note: constraining on branch=master makes upgrades easier

required = [
  "github.com/fenollp/gox",
  "github.com/golang/lint/golint",
  "honnef.co/go/tools/cmd/megacheck",
  "github.com/wadey/gocovmerge",
  "github.com/kyoh86/richgo",
  "github.com/golang/protobuf/protoc-gen-go",
]

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/kyoh86/richgo"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/googleapis/gnostic"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/color"

[[constraint]]
  branch = "master"
  name = "github.com/cardigann/harhar"

[[constraint]]
  branch = "master"
  name = "github.com/docopt/docopt-go"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2" #gnostic uses this import name

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/logutils"

[[constraint]]
  branch = "master"
  name = "github.com/sebcat/har"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "github.com/wadey/gocovmerge"

[[constraint]]
  branch = "master"
  name = "github.com/fenollp/gox"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/tools"
