name: lint

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: reviewdog/action-golangci-lint@v1
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: '--config=.golangci.toml'
