name: master

on:
  push: {branches: [master]}

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: grep -F . Tagfile && echo TAG=$(cat Tagfile) >>$GITHUB_ENV

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/bake-action@v1.2.0
      with:
        files: ./docker-bake.hcl
        targets: ${{ env.TARGET }}
        set: |
          *.cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:${{ env.TARGET }},mode=max
      env:
        TARGET: goreleaser-dist

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        ./monkey -h | grep monkey
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep -F $(cat Tagfile)
        ./monkey --version | grep -F $(cat Tagfile)

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./dist/*
        commit: master       # Required to push tag
        tag: ${{ env.TAG }}  # Required to push tag
        token: ${{ secrets.GITHUB_TOKEN }}
