name: master

on:
  push: {branches: [master]}

jobs:
  master:
    runs-on: ubuntu-latest
    env:
      TARGET: goreleaser-dist
    steps:
    - uses: actions/checkout@v2

    - id: tag
      run: grep -F . Tagfile && echo TAG=$(cat Tagfile) >>$GITHUB_ENV

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache/${{ env.TARGET }}
        key: ${{ runner.os }}-buildx-${{ env.TARGET }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ env.TARGET }}-

    - uses: docker/bake-action@v1.2.0
      with:
        files: ./docker-bake.hcl
        targets: ${{ env.TARGET }}
        set: |
          *.cache-from=type=local,src=/tmp/.buildx-cache/${{ env.TARGET }}
          *.cache-to=type=local,dest=/tmp/.buildx-cache/${{ env.TARGET }}-new

    # TODO: remove. Cf: https://github.com/moby/buildkit/issues/1850
    - run: |
        rm -rf /tmp/.buildx-cache/${{ env.TARGET }}
        mv /tmp/.buildx-cache/${{ env.TARGET }}-new /tmp/.buildx-cache/${{ env.TARGET }}

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        SHORT_COMMIT=$(cut -c-7 <<<$GITHUB_SHA)
        ./monkey -h | grep $SHORT_COMMIT
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep -F $(cat Tagfile)
        ./monkey --version | grep $SHORT_COMMIT

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./dist/*
        commit: master                 # Required to push tag
        tag: ${{ steps.tag.env.TAG }}  # Required to push tag
        token: ${{ secrets.GITHUB_TOKEN }}
