name: pr

on:
  pull_request: {}

jobs:
  tagfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Ensure Tagfile is usable
      run: grep -F . Tagfile

    - name: Checkout master Tagfile
      uses: actions/checkout@v2
      with:
        ref: master
        path: ./master-Tagfile

    - name: Ensure Tagfile has changes
      run: '! diff -q Tagfile ./master-Tagfile/Tagfile'

  ci-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/bake-action@v1.2.0
      with:
        files: ./docker-bake.hcl
        targets: ${{ env.TARGET }}
        set: |
          *.cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:${{ env.TARGET }}
          *.cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:${{ env.TARGET }},mode=max
      env:
        TARGET: ci-checks

  goreleaser-dist:
    needs: [ci-checks]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/bake-action@v1.2.0
      with:
        files: ./docker-bake.hcl
        targets: ${{ env.TARGET }}
        set: |
          *.cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:${{ env.TARGET }}
          *.cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:${{ env.TARGET }},mode=max
      env:
        TARGET: goreleaser-dist

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        SHORT_COMMIT=$(cut -c-7 <<<$GITHUB_SHA)
        ./monkey -h | grep $SHORT_COMMIT
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep -F $(cat Tagfile)
        ./monkey --version | grep $SHORT_COMMIT
