name: pr

on:
  push:
  pull_request:

#   on: {push: {branches: [master]}}
#   => builds master => Publish tag+release w/ --target=goreleaser-dist
#   => builds tag => check monkey action

jobs:
  tagfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Ensure Tagfile is usable
      run: grep -F . Tagfile

    - name: Checkout master Tagfile
      uses: actions/checkout@v2
      with:
        ref: master
        path: ./master-Tagfile

    - name: Ensure Tagfile has changes
      run: '! diff -q Tagfile ./master-Tagfile/Tagfile'

  ci-checks:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/monkey:cache
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:cache
        cache-to: type=inline
        #https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
        target: ci-checks

  goreleaser-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/monkey:cache
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monkey:cache
        cache-to: type=inline
        #https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
        target: goreleaser-dist
        outputs: ./dist

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        SHORT_COMMIT=$(cut -c-7 <<<$GITHUB_SHA)
        ./monkey -h | grep $SHORT_COMMIT
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep -F $(cat Tagfile)
        ./monkey --version | grep $SHORT_COMMIT
