name: pr

on:
  pull_request:

# PR to master => build + require changes to Tagfile + grep -F . Tagfile => merge
#   on: {push: {branches: [master]}}
#   => builds master => Publish tag+release w/ --target=goreleaser-dist
#   => builds tag => check monkey action

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Ensure Tagfile is usable
      run: grep -F . Tagfile

    # - name: Lint
    #   run: |
    #     sudo apt-get install -y silversearcher-ag  # For golint.sh
    #     ag --version
    #     [[ $(git grep -l pwdID | wc -l) = 2 ]]  # lint: pwdID fiddling happens only in one place
    #     make lint

    # - name: Mod
    #   run: |
    #     go mod tidy
    #     go mod verify
    #     git --no-pager diff && [[ $(git --no-pager diff --name-only | wc -l) = 0 ]]

    # - name: Test
    #   run: |
    #     make test.ci
    #     git --no-pager diff && [[ $(git --no-pager diff --name-only | wc -l) = 0 ]]

    - name: Build with goreleaser
      run: mkdir dist && DOCKER_BUILDKIT=1 docker build --target=goreleaser-dist -o dist/ .

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        SHORT_COMMIT=$(cut -c-7 <<<$GITHUB_SHA)
        ./monkey -h | grep $SHORT_COMMIT
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep $(cat Tagfile)
        ./monkey --version | grep $SHORT_COMMIT
        rm ./monkey

    - name: Checkout master Tagfile
      uses: actions/checkout@v2
      with:
        ref: master
        path: ./dist/master-Tagfile
    - name: Ensure Tagfile has changes
      run: '! diff -q Tagfile ./dist/master-Tagfile/Tagfile'

  #   - name: Publish
  #     uses: goreleaser/goreleaser-action@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       version: latest # FIXME: https://github.com/goreleaser/goreleaser-action/issues/157
  #       args: release --rm-dist
  #     if: startsWith(github.ref, 'refs/tags/')


  # install-on-ubuntu:
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: goreleaser
  #   steps:
  #   - run: '! which monkey'
  #   - uses: FuzzyMonkeyCo/action-monkey@v1
  #     with:
  #       command: version
  #       github_token: ${{ secrets.github_token }}

  # install-on-macos:
  #   runs-on: macos-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: goreleaser
  #   steps:
  #   - run: '! which monkey'
  #   - uses: FuzzyMonkeyCo/action-monkey@v1
  #     with:
  #       command: version
  #       github_token: ${{ secrets.github_token }}

  # install-on-windows:
  #   runs-on: windows-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: goreleaser
  #   steps:
  #   - run: '! which monkey'
  #     shell: bash
  #   - uses: FuzzyMonkeyCo/action-monkey@v1
  #     with:
  #       command: version
  #       github_token: ${{ secrets.github_token }}
