name: push

on:
  push: {}

jobs:
  buildkit-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: DOCKER_BUILDKIT=1 docker build -o . .
    - run: ./monkey version
    - run: sha256sum ./monkey
    - run: rm ./monkey

    - run: DOCKER_BUILDKIT=1 docker build --platform=darwin/amd64 -o . .
    - run: sha256sum ./monkey
    - run: rm ./monkey

    - run: DOCKER_BUILDKIT=1 docker build --platform=windows/amd64 -o . .
    - run: sha256sum ./monkey.exe
    - run: rm ./monkey.exe
