name: push

on:
  push: {}

jobs:
  buildkit--ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: DOCKER_BUILDKIT=1 docker build --platform=local -o . .
    - run: ./monkey

  buildkit--macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build --platform=local -o . .
    - run: ./monkey

  buildkit--windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build --platform=local -o . .
    - run: ./monkey.exe
