name: shellcheck

on:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
# - godownloader -r FuzzyMonkeyCo/monkey -o .godownloader.sh .goreleaser.yml
# - shellcheck $(git ls-files | grep '.sh$' | grep -vF .godownloader.sh) #TODO: fix godownloader warnings upstream
