name: testaction

on:
  create: # runs on branch or tag creation but want only tag

jobs:

  on_ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: FuzzyMonkeyCo/action-monkey@v1
      with:
        command: lint
        github_token: ${{ secrets.github_token }}

  on_macos:
    name: macos
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: FuzzyMonkeyCo/action-monkey@v1
      with:
        command: lint
        github_token: ${{ secrets.github_token }}

  on_windows:
    name: windows
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: FuzzyMonkeyCo/action-monkey@v1
      with:
        command: lint
        github_token: ${{ secrets.github_token }}
